services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
volumes:
  postgres-data:
  redis-data:
