openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  /session:
    post:
      summary: Create session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
