openapi: 3.0.1
info:
  title: Park42
  version: v1
paths:
  /session:
    post:
      summary: Create session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            example:
              email: alice@email.com
              password: password
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /price:
    post:
      summary: Calculate reservation price
      description: |
        Calculates the total reservation price using daily fees. Both `start_at`
        and `end_at` must be ISO 8601 timestamps. The time component is ignored
        when determining the number of days.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                start_at:
                  type: string
                  format: date-time
                  example: "2025-06-18T00:00:00Z"
                end_at:
                  type: string
                  format: date-time
                  example: "2025-06-19T00:00:00Z"
              required:
                - start_at
                - end_at
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: integer
                  currency:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
